import { _decorator, cclegacy } from 'cc';

export namespace GameConst {
    export const BgmVolume = 1;
    export const SoundVolume = 1;
    export const DetailShowLv = 10;
    export const ChestRepeatStart = 6;
    export const SkinShowLv = 5;
    export const PropUndoLockLv = 2;
    export const PropWandLockLv = 3;
    export const PropShuffleLockLv = 5;
    export const PropUndoCost = 100;
    export const PropWandCost = 200;
    export const PropShuffleCost = 150;
    export const INTERSTITIAL_CD_S = 60;
    export const INTERSTITIAL_CollectedLimited = 10;
    export const INTERSTITIAL_LevelLimited = 3;
    export const INTERSTITIAL_Level = 4;
    export const ORIGINAL_TILESET_ID = 1;
    export const TILE_SWAP_PERCENT = 50;
    export const Fresh_CD = 20;
    export const Hint_CD = 20;
    export const REVIVE_COIN_COUNT = 300;
    export const CHALLENGE_START = 56;
    export const CHALLENGE_LEVEL = 732;
    export const CHALLENGE_DIFFICULTY = 20;
    export const CHALLENGE_ALGORUTHM = 1;
    export const CHALLENGE_PARAM = 50;
    export const CHALLENGE_STAR_NUM = [5, 10];
    export const CHALLENGE_STAR_PASSED = 10;
    export const CHALLENGE_OPEN_LEVEL = 5;
    export const TASK_OPEN_LEVEL = 10;
    export const Evaluation_OPEN_LEVEL = 35;
    export const Evaluation_REPEAT_LEVEL = 30;
    export const Evaluation_OPEN_LEVEL_IOS = [6, 30];
    export const PASS_OPEN_LEVEL = 80;
    export const PASS_OPEN_TIME_TYPE = 7;
    export const PASS_OPEN_TIME = [4];
    export const MAX_LEVEL_CFG = 4720;
    export const CHALLENGE_BG_ID = 14;
    export const GOLDEN_PIG_LEVEL = 26;
    export const GOLDEN_PIG_PROGRESS = 25;
    export const GOLDEN_PIG_MAX_COIN = 1500;
    export const GOLDEN_PIG_MIN_COIN = 600;
    export const GOLDEN_PIG_DAILY_POP_CNT = 1;
    export const GOLDEN_PIG_POP_PASSLV_LIMITED = 5;
    export const MAIN_BG_ID = 14;
    export const EVALUATE_COUNT = 8;
    export const WINSTREAK_OPEN_LEVEL = 40;
    export const WINSTREAK_OPEN_TIME_TYPE = 7;
    export const WINSTREAK_OPEN_TIME = [6, 7];
    export const WINSTREAK_V2_OPEN_LEVEL = 40;
    export const WINSTREAK_V2_OPEN_TIME_TYPE = 7;
    export const WINSTREAK_V2_OPEN_TIME = [1, 2, 3];
    export const RankShowLv = 10;
    export const AdCoinShowLv = 11;
    export const AdCoinNum = 50;
    export const GOLDTOURNAMENT_OPEN_LEVEL = 60;
    export const GOLDTOURNAMENT_OPEN_TIME_TYPE = 7;
    export const GOLDTOURNAMENT_OPEN_TIME = [4, 5];
    export const GOLDTOURNAMENT_V2_OPEN_LEVEL = 60;
    export const GOLDTOURNAMENT_V2_OPEN_TIME_TYPE = 7;
    export const GOLDTOURNAMENT_V2_OPEN_TIME = [1, 2];
    export const GOLDTILE_LEVEL_MAX_NUM = 9;
    export const GOLDTOURNAMENT_GOLDTILE_NUM = 3;
    export const GOLDTILE_COIN_NUM = 6;
    export const PASS_OPEN_ORDER = 1;
    export const WINSTREAK_OPEN_ORDER = 2;
    export const WINSTREAK_V2_OPEN_ORDER = 3;
    export const GOLDTOURNAMENT_OPEN_ORDER = 4;
    export const GOLDTOURNAMENT_V2_OPEN_ORDER = 4;
    export const RACE_OPEN_ORDER = 5;
    export const TOYRACE_OPEN_ORDER = 6;
    export const STARLEAGUE_OPEN_ORDER = 7;
    export const PROP_LIGHT_AD_NUM = 3;
    export const NOTIFY_OPEN_LEVEL = 11;
    export const Shop_Open_Level = 3;
    export const Shop_Close_Coin = 25;
    export const Turntable_Opem_Level = 5;
    export const TurntableSpinNum = 6;
    export const AdBox_Level_Time = 60;
    export const AdBox_Player_Prop_Num1 = 3;
    export const AdBox_Player_Prop_Num2 = 5;
    export const AdBox_80_Level_Before = [9, 10, 12, 16, 17, 19, 21, 22, 26, 27, 30, 32, 35, 38, 39, 43, 44, 47, 48, 51, 54, 57, 59, 62, 65, 68, 70, 71, 74, 75, 76, 78];
    export const AdBox_80_Level_After = 3;
    export const AdBox_delay_Time = 15;
    export const AdBox_interval_Time = 30;
    export const AdNext_Delay_Time = 2;
    export const RACE_OPEN_LEVEL = 50;
    export const RACE_OPEN_TIME_TYPE = 7;
    export const RACE_OPEN_TIME = [5, 6];
    export const RACE_DAILY_CNT = 3;
    export const RACE_AI_CNT = 9;
    export const REMOVE_ADS_PACKIDS = [601, 202];
    export const REMOVE_ADS_DASK = 601;
    export const STAR_LEAGUE_OPEN_LEVEL = 25;
    export const STAR_LEAGUE_WEEK_OPEN_DAY = [6, 7];
    export const STAR_LEAGUE_COUNT = 60;
    export const ToyRaceUnlockLevel = 15;
    export const ToyRaceOpenDays = 3;
    export const ToyRaceSpaceDays = 4;
    export const ToyRaceMatchCount = 5;
    export const ToyRaceMaxProgress = 15;
    export const TOY_RACE_OPEN_TIME = [3, 4, 5];
    export const Unlock_Space_Open_Level = 9;
    export const MINE_OPEN_LEVEL = 30;
    export const MINE_OPEN_TIME_TYPE = 7;
    export const MINE_OPEN_TIME = [1, 2, 3];
    export const MINE_START_PICKAXE = 2;
    export const NORMAL_PICKAXE_NUM = '1|20,2|45,3|35';
    export const MINE_OPEN_ORDER = 8;
    export const BONUS_WAND_UNLOCK_LEVEL = 20;
    export const BONUS_WAND_WINCOUNT = 5;
    export const BONUS_ALGORUTHM = 3;
    export const BONUS_PARAM = 22;
    export const BONUS_TILE_COIN = 1;
    export const FriendListOpenLevel = 2;
    export const FriendListIntervalLevel = 1;
    export const RankingListOpenLevel = 4;
    export const RankingListIntervalLevel = 1;
    export const ReturnRewards = 100;
    export const GiftPushMaxNum = 3;
    export const ChanllengeStartLevel = 3;
    export const ChanllengeIntervalLevel = 3;
    export const ChanllengeAIAddNeedTime = [4.5, 10.5];
}

export enum ITEM {
    Coin = 0,
    Star = 1,
    Energy = 2,
    Wisdom = 3,
    Back = 10,
    Hint = 11,
    Fresh = 12,
    Light = 20,
    GoldenTile = 21,
    TileCoin = 22,
    GoldFlower = 97,
    ChallengeStar = 98,
    Ad = 99,
    PickAxe = 101
}